### PR TITLE
First version of assessment 4

### PR DESCRIPTION
**Pull request by chloedb**
cdb-a4dig245.surge.sh

### CODE REVIEW

**Comment by jfarmer** [comment]
The URL doesn't work

**Comment by chloedb** [comment]
oh no! @jfarmer i’ll re-run the surge!

**Comment by jfarmer** [comment]
The idea here is to implement one of your wireframes using a CSS framework of your choosing. It doesn't seem like you used any framework. Try using Bootstrap or Bulma to make things look like your wireframes. They make it much easier to control how elements line up.

Most frameworks divide the page into 12 columns. You might say: "Here's a row containing two columns, the first one is 3 grid units wide and the second is 9 grid units wide." That would get you a sidebar that is 25% the width of the page and a main content area that is 75% the width of the page, for example.

The frameworks give you pre-defined CSS classes to express things like "row", "3 grid units wide", etc.

**Comment by chloedb** [comment]
That makes way more sense in terms of what a framework does. I'll reevaluate and find a different one!

**Pull request closed without merging**
